name: Test

env:
  DEFAULT_POETRY_VERSION: "2.1.0"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==${{ env.DEFAULT_POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Test
        run: poetry run pytest -vra
